#!/usr/bin/env python
"""Preregistered zero-integration K7a projected-Jacobian audit.

The script immutably extends 157.  It replaces delta_fs and U_fs by the
compensated density and momentum sources D and M, includes the mandatory
time-dependent-basis connection T' T^-1, and compares an explicit projected
RHS against (T' + T A_y) T^-1.  No ODE evolution or score is allowed.
"""

from __future__ import annotations

from pathlib import Path


SOURCE = Path(__file__).with_name(
    "157_script_A2_K4_C7_7c_jacobian_scaling_and_fd_audit.py"
)
source_text = SOURCE.read_text(encoding="utf-8")
MARKER = "'''\n\nextended = source_text.replace"
if source_text.count(MARKER) != 1:
    raise RuntimeError("script 157 K7a extension marker is not unique")

addition = r'''    (
        "K7a_projected_jacobian_calculation",
        '            envelope_exact = (\n',
        '            projected_bg = background(x_current)\n'
        '            Og = projected_bg["Omega_gamma"]\n'
        '            On = projected_bg["Omega_fs"]\n'
        '            Ob = projected_bg["Omega_b"]\n'
        '            Oc = projected_bg["Omega_c"]\n'
        '            Of = projected_bg["Omega_f"]\n'
        '            z_bg = projected_bg["z"]\n'
        '            ell = 2.0*(projected_bg["q"] + 1.0)\n'
        '            c_numerator = (\n'
        '                fc*mu*z_bg + g2*z_bg**(p+2.0)/(p+1.0)\n'
        '            )\n'
        '            beta_c = (\n'
        '                fc*mu*z_bg\n'
        '                +(p+2.0)*g2*z_bg**(p+2.0)/(p+1.0)\n'
        '            )/c_numerator\n'
        '            beta_f = (\n'
        '                p-projected_bg["g"]/(1.0-0.5*projected_bg["g"])\n'
        '            )\n'
        '            Op = np.asarray([\n'
        '                -ell*Og,\n'
        '                -ell*On,\n'
        '                (1.0-ell)*Ob,\n'
        '                (beta_c-ell)*Oc,\n'
        '                (beta_f-ell)*Of,\n'
        '            ])\n'
        '            Wg = 2.0*Og + 1.5*Ob\n'
        '            Wf = 1.5*delta*Of\n'
        '            Wgp = 2.0*Op[0] + 1.5*Op[2]\n'
        '            Wfp = 1.5*delta*Op[4]\n'
        '            T = np.eye(len(STATE_NAMES))\n'
        '            T[3, :] = 0.0\n'
        '            T[3, 2] = Og\n'
        '            T[3, 3] = On\n'
        '            T[3, 4] = Ob\n'
        '            T[3, 5] = Oc\n'
        '            T[3, 11] = Of\n'
        '            T[7, :] = 0.0\n'
        '            T[7, 6] = Wg\n'
        '            T[7, 7] = 2.0*On\n'
        '            T[7, 12] = Wf\n'
        '            Tp = np.zeros_like(T)\n'
        '            Tp[3, 2] = Op[0]\n'
        '            Tp[3, 3] = Op[1]\n'
        '            Tp[3, 4] = Op[2]\n'
        '            Tp[3, 5] = Op[3]\n'
        '            Tp[3, 11] = Op[4]\n'
        '            Tp[7, 6] = Wgp\n'
        '            Tp[7, 7] = 2.0*Op[1]\n'
        '            Tp[7, 12] = Wfp\n'
        '            Tinv = np.linalg.inv(T)\n'
        '            frozen_projected = T@physical_jacobian@Tinv\n'
        '            connection = Tp@Tinv\n'
        '            transformed_projected = frozen_projected + connection\n'
        '            def transformation_at(x_value):\n'
        '                local_bg = background(x_value)\n'
        '                local_Og = local_bg["Omega_gamma"]\n'
        '                local_On = local_bg["Omega_fs"]\n'
        '                local_Ob = local_bg["Omega_b"]\n'
        '                local_Oc = local_bg["Omega_c"]\n'
        '                local_Of = local_bg["Omega_f"]\n'
        '                local_T = np.eye(len(STATE_NAMES))\n'
        '                local_T[3, :] = 0.0\n'
        '                local_T[3, 2] = local_Og\n'
        '                local_T[3, 3] = local_On\n'
        '                local_T[3, 4] = local_Ob\n'
        '                local_T[3, 5] = local_Oc\n'
        '                local_T[3, 11] = local_Of\n'
        '                local_T[7, :] = 0.0\n'
        '                local_T[7, 6] = 2.0*local_Og + 1.5*local_Ob\n'
        '                local_T[7, 7] = 2.0*local_On\n'
        '                local_T[7, 12] = 1.5*delta*local_Of\n'
        '                return local_T\n'
        '            Tprime_fd_audit = {}\n'
        '            for t_step in (1e-4, 1e-5, 1e-6):\n'
        '                Tp_fd = (\n'
        '                    transformation_at(x_current+t_step)\n'
        '                    -transformation_at(x_current-t_step)\n'
        '                )/(2.0*t_step)\n'
        '                Tprime_fd_audit[str(t_step)] = {\n'
        '                    "max_abs_error": float(np.max(np.abs(Tp_fd-Tp))),\n'
        '                    "relative_frobenius_error": float(\n'
        '                        np.linalg.norm(Tp_fd-Tp)\n'
        '                        /max(np.linalg.norm(Tp), 1e-300)\n'
        '                    ),\n'
        '                }\n'
        '            s2p = projected_bg["s2"]\n'
        '            qp = projected_bg["q"]\n'
        '            gp = projected_bg["g"]\n'
        '            grp = projected_bg["gr"]\n'
        '            inv1r = 1.0/(1.0+projected_bg["loading"])\n'
        '            load_fraction = projected_bg["loading"]*inv1r\n'
        '            Ah = (\n'
        '                (2.0/3.0)*(Og+On)\n'
        '                +0.5*(Ob+Oc)+0.5*delta*Of\n'
        '            )\n'
        '            def explicit_projected_rhs(projected_state):\n'
        '                (\n'
        '                    hp, etap, dgp, Dp, dbp, dcp, Ugp, Mp,\n'
        '                    sigp, L3p, L4p, dfp, Ufp,\n'
        '                ) = projected_state\n'
        '                dnp = (\n'
        '                    Dp-Og*dgp-Ob*dbp-Oc*dcp-Of*dfp\n'
        '                )/On\n'
        '                Unp = (Mp-Wg*Ugp-Wf*Ufp)/(2.0*On)\n'
        '                hx = 3.0*Dp + 2.0*s2p*etap\n'
        '                etax = Mp\n'
        '                dgx = -(4.0/3.0)*s2p*Ugp-(2.0/3.0)*hx\n'
        '                Dx = (\n'
        '                    -ell*Dp + Ob*dbp + beta_c*Oc*dcp\n'
        '                    +beta_f*Of*dfp -(2.0/3.0)*s2p*Mp -Ah*hx\n'
        '                    +Oc*grp*(dfp-dcp)\n'
        '                    +Of*(\n'
        '                        -3.0*(2.0-delta)*dfp\n'
        '                        -9.0*delta*(2.0-delta)*Ufp\n'
        '                        -3.0*(2.0-delta)*gp*Ufp\n'
        '                    )\n'
        '                )\n'
        '                dbx = -s2p*Ugp-0.5*hx\n'
        '                dcx = -0.5*hx+grp*(dfp-dcp)\n'
        '                Ugx = (\n'
        '                    qp*Ugp-load_fraction*Ugp+0.25*inv1r*dgp\n'
        '                )\n'
        '                Mx = (\n'
        '                    (-qp-2.0)*Mp+0.5*Dp\n'
        '                    +(1.5*Ob-Wg*load_fraction)*Ugp\n'
        '                    +(0.25*Wg*inv1r-0.5*Og)*dgp\n'
        '                    -0.5*Ob*dbp-0.5*Oc*dcp+Of*dfp\n'
        '                    -2.0*On*sigp\n'
        '                    +(1.5*delta*Of*(beta_f+2.0)+3.0*Of*gp)*Ufp\n'
        '                )\n'
        '                sigx = (\n'
        '                    (2.0/15.0)*hx+(4.0/5.0)*etax\n'
        '                    +(4.0/15.0)*s2p*Unp-(3.0/10.0)*L3p\n'
        '                )\n'
        '                L3x = (\n'
        '                    -qp*L3p+(6.0/7.0)*s2p*sigp-(4.0/7.0)*L4p\n'
        '                )\n'
        '                L4x = -2.0*qp*L4p+(4.0/9.0)*s2p*L3p\n'
        '                dfx = (\n'
        '                    -3.0*(2.0-delta)*dfp-delta*s2p*Ufp\n'
        '                    -0.5*delta*hx-9.0*delta*(2.0-delta)*Ufp\n'
        '                    -3.0*(2.0-delta)*gp*Ufp\n'
        '                )\n'
        '                Ufx = (\n'
        '                    (qp+2.0)*Ufp+dfp/delta\n'
        '                    +(2.0/delta)*gp*Ufp\n'
        '                )\n'
        '                return np.asarray([\n'
        '                    hx, etax, dgx, Dx, dbx, dcx, Ugx, Mx,\n'
        '                    sigx, L3x, L4x, dfx, Ufx,\n'
        '                ])\n'
        '            projected_explicit = np.empty_like(physical_jacobian)\n'
        '            projected_zero = explicit_projected_rhs(\n'
        '                np.zeros(len(STATE_NAMES))\n'
        '            )\n'
        '            for projected_column in range(len(STATE_NAMES)):\n'
        '                projected_basis = np.zeros(len(STATE_NAMES))\n'
        '                projected_basis[projected_column] = 1.0\n'
        '                projected_explicit[:, projected_column] = (\n'
        '                    explicit_projected_rhs(projected_basis)-projected_zero\n'
        '                )\n'
        '            projected_difference = (\n'
        '                projected_explicit-transformed_projected\n'
        '            )\n'
        '            physical_eigs_k7 = np.sort_complex(\n'
        '                np.linalg.eigvals(physical_jacobian)\n'
        '            )\n'
        '            frozen_eigs_k7 = np.sort_complex(\n'
        '                np.linalg.eigvals(frozen_projected)\n'
        '            )\n'
        '            best_Tprime_relative_error = min(\n'
        '                item["relative_frobenius_error"]\n'
        '                for item in Tprime_fd_audit.values()\n'
        '            )\n'
        '            projected_relative_error = float(\n'
        '                np.linalg.norm(projected_difference)\n'
        '                /max(np.linalg.norm(transformed_projected), 1e-300)\n'
        '            )\n'
        '            projected_max_abs_error = float(\n'
        '                np.max(np.abs(projected_difference))\n'
        '            )\n'
        '            frozen_spectrum_relative_error = float(\n'
        '                np.max(np.abs(frozen_eigs_k7-physical_eigs_k7))\n'
        '                /max(1.0, float(np.max(np.abs(physical_eigs_k7))))\n'
        '            )\n'
        '            transform_condition = float(np.linalg.cond(T))\n'
        '            projected_max_abs = float(\n'
        '                np.max(np.abs(transformed_projected))\n'
        '            )\n'
        '            zero_limit_residuals = np.asarray([\n'
        '                (-0.0-3.0*(2.0/3.0))-(-2.0),\n'
        '                (-(-1.0)-2.0)-(-1.0),\n'
        '                0.5-0.5,\n'
        '                (-2.0*rn)-(-2.0*rn),\n'
        '                (0.25*(2.0*rg)-0.5*rg)-0.0,\n'
        '            ])\n'
        '            zero_limit_max_residual = float(\n'
        '                np.max(np.abs(zero_limit_residuals))\n'
        '            )\n'
        '            checks[f"{mode}_{surface}_K7a_Omega_fs_positive"] = On > 0.0\n'
        '            checks[f"{mode}_{surface}_K7a_transform_condition"] = (\n'
        '                transform_condition < 1e4\n'
        '            )\n'
        '            checks[f"{mode}_{surface}_K7a_Tprime_fd"] = (\n'
        '                best_Tprime_relative_error < 1e-8\n'
        '            )\n'
        '            checks[f"{mode}_{surface}_K7a_projected_relative"] = (\n'
        '                projected_relative_error < 1e-12\n'
        '            )\n'
        '            checks[f"{mode}_{surface}_K7a_projected_absolute"] = (\n'
        '                projected_max_abs_error < 1e-10\n'
        '            )\n'
        '            checks[f"{mode}_{surface}_K7a_frozen_spectrum"] = (\n'
        '                frozen_spectrum_relative_error < 1e-12\n'
        '            )\n'
        '            checks[f"{mode}_{surface}_K7a_projected_safety"] = (\n'
        '                projected_max_abs < 1e4\n'
        '            )\n'
        '            checks[f"{mode}_{surface}_K7a_zero_limit"] = (\n'
        '                zero_limit_max_residual < 1e-14\n'
        '            )\n'
        '            K7a_projected_audit = {\n'
        '                "Omega_fs": float(On),\n'
        '                "ell": float(ell),\n'
        '                "beta_c": float(beta_c),\n'
        '                "beta_f": float(beta_f),\n'
        '                "transform_determinant": float(np.linalg.det(T)),\n'
        '                "transform_condition_2": transform_condition,\n'
        '                "Tprime_fd_audit": Tprime_fd_audit,\n'
        '                "best_Tprime_relative_error": best_Tprime_relative_error,\n'
        '                "projected_relative_frobenius_error": projected_relative_error,\n'
        '                "projected_max_abs_error": projected_max_abs_error,\n'
        '                "frozen_spectrum_relative_error": frozen_spectrum_relative_error,\n'
        '                "physical_max_abs": float(np.max(np.abs(physical_jacobian))),\n'
        '                "frozen_projected_max_abs": float(\n'
        '                    np.max(np.abs(frozen_projected))\n'
        '                ),\n'
        '                "connection_max_abs": float(np.max(np.abs(connection))),\n'
        '                "full_projected_max_abs": projected_max_abs,\n'
        '                "full_projected_singular_max": float(\n'
        '                    np.linalg.svd(transformed_projected, compute_uv=False)[0]\n'
        '                ),\n'
        '                "physical_spectral_radius": float(\n'
        '                    np.max(np.abs(physical_eigs_k7))\n'
        '                ),\n'
        '                "full_projected_spectral_radius": float(\n'
        '                    np.max(np.abs(np.linalg.eigvals(transformed_projected)))\n'
        '                ),\n'
        '                "zero_limit_max_residual": zero_limit_max_residual,\n'
        '                "interpretation": (\n'
        '                    "full projected spectrum includes Tprime*Tinv and is not "\n'
        '                    "a similarity invariant"\n'
        '                ),\n'
        '            }\n'
        '            envelope_exact = (\n',
    ),
    (
        "K7a_projected_audit_output",
        '                "scaling_and_fd_audit": scaling_fd_audit,\n',
        '                "K7a_projected_jacobian_audit": K7a_projected_audit,\n'
        '                "scaling_and_fd_audit": scaling_fd_audit,\n',
    ),
    (
        "K7a_test_identity",
        '"test": "A2-K4 C7.7c Jacobian scaling and FD audit"',
        '"test": "A2-K4 C7.7c-K7a projected D-M Jacobian audit"',
    ),
    (
        "K7a_execution_verdict",
        '"CAPTURED_C7_7C_JACOBIAN_SCALING_FD_AUDIT"',
        '"PASS_C7_7C_K7A_PROJECTED_JACOBIAN"',
    ),
    (
        "K7a_physical_verdict",
        '"diagnostic profile only; no physical verdict and no score change"',
        '"K7a algebraic and Jacobian gate only; no evolution and no score change"',
    ),
'''

extended = source_text.replace(
    MARKER, addition + "'''\n\nextended = source_text.replace", 1
)
code = compile(extended, str(Path(__file__)), "exec")
exec(code, {"__name__": "__main__", "__file__": str(Path(__file__))})
