#!/usr/bin/env python
"""Fail-closed successor of the physical-mu K7b gate 175.

The physical calculation is still generated by the immutable 172 -> 169 ->
166 chain and the physical-mu exporter 174.  This wrapper changes only the
rank metadata validation and adds an explicit negative-test fault injection.
No equation, coefficient, tolerance, background, or RHS is changed.
"""

from __future__ import annotations

from pathlib import Path


SOURCE = Path(__file__).with_name(
    "172_script_A2_K4_C7_7c_K7b3b_hard_constrained_constraint_gate.py"
)
source_text = SOURCE.read_text(encoding="utf-8")

identity_replacements = (
    (
        "171_script_A2_K4_C7_7c_K7b3b_hard_constrained_slice_corrected_export.py",
        "174_script_A2_K4_C7_7c_K7b3b1_slice_and_physical_mu_export.py",
    ),
    (
        "A2-K4 C7.7c-K7b.3b hard-constrained standard coefficient gate",
        "A2-K4 C7.7c-K7b.3b.2 fail-closed physical-mu coefficient gate",
    ),
    (
        "PASS_C7_7C_K7B3B_HARD_CONSTRAINED_STANDARD_GATE",
        "PASS_C7_7C_K7B3B2_FAIL_CLOSED_PHYSICAL_MU_GATE",
    ),
    (
        "REVIEW_C7_7C_K7B3B_HARD_CONSTRAINED_STANDARD_UNCLOSED",
        "REVIEW_C7_7C_K7B3B2_FAIL_CLOSED_PHYSICAL_MU_UNCLOSED",
    ),
)
for old, new in identity_replacements:
    if source_text.count(old) != 1:
        raise RuntimeError(f"script 172 identity marker count changed: {old!r}")
    source_text = source_text.replace(old, new, 1)

old_compile = '''code = compile(source_text, str(Path(__file__)), "exec")
exec(code, {"__name__": "__main__", "__file__": str(Path(__file__))})
'''
patch_generated_gate = '''parser_old = """    parser.add_argument("--dps", type=int, default=80)
    return parser
"""
parser_new = """    parser.add_argument("--dps", type=int, default=80)
    parser.add_argument(
        "--fault-remove-rank-key",
        choices=("none", "reduced_rank", "free_count", "both"),
        default="none",
        help="negative-control metadata fault injection; never changes physics",
    )
    return parser
"""
if source_text.count(parser_old) != 1:
    raise RuntimeError("generated parser marker is not unique")
source_text = source_text.replace(parser_old, parser_new, 1)

solver_old = """    hp_solver = dict(hp_solver_all.get(args.mode, {}))
    D_activity_relative_error = abs(
"""
solver_new = """    hp_solver = dict(hp_solver_all.get(args.mode, {}))
    rank_fault_removed = []
    if args.fault_remove_rank_key in ("reduced_rank", "both"):
        hp_solver.pop("reduced_rank", None)
        rank_fault_removed.append("reduced_rank")
    if args.fault_remove_rank_key in ("free_count", "both"):
        hp_solver.pop("free_count", None)
        rank_fault_removed.append("free_count")
    D_activity_relative_error = abs(
"""
if source_text.count(solver_old) != 1:
    raise RuntimeError("generated hp_solver marker is not unique")
source_text = source_text.replace(solver_old, solver_new, 1)

rank_old = """    checks["reduced_standard_system_full_rank"] = (
        hp_solver.get("reduced_rank") == hp_solver.get("free_count")
    )
"""
rank_new = """    rank_keys_present = all(
        key in hp_solver for key in ("reduced_rank", "free_count")
    )
    rank_values_plain_int = (
        rank_keys_present
        and type(hp_solver["reduced_rank"]) is int
        and type(hp_solver["free_count"]) is int
    )
    checks["reduced_standard_rank_keys_present"] = rank_keys_present
    checks["reduced_standard_rank_values_plain_int"] = rank_values_plain_int
    checks["reduced_standard_system_full_rank"] = (
        rank_values_plain_int
        and hp_solver["reduced_rank"] == hp_solver["free_count"]
    )
"""
if source_text.count(rank_old) != 1:
    raise RuntimeError("generated fail-open rank marker is not unique")
source_text = source_text.replace(rank_old, rank_new, 1)

payload_old = """        "K7b3b_hard_constrained_standard_solver": hp_solver,
        "D_activity_relative_error": float(D_activity_relative_error),
"""
payload_new = """        "rank_fault_injection": {
            "requested": args.fault_remove_rank_key,
            "removed": rank_fault_removed,
        },
        "K7b3b_hard_constrained_standard_solver": hp_solver,
        "D_activity_relative_error": float(D_activity_relative_error),
"""
if source_text.count(payload_old) != 1:
    raise RuntimeError("generated payload marker is not unique")
source_text = source_text.replace(payload_old, payload_new, 1)

code = compile(source_text, str(Path(__file__)), "exec")
exec(code, {"__name__": "__main__", "__file__": str(Path(__file__))})
'''
if source_text.count(old_compile) != 1:
    raise RuntimeError("script 172 final compile marker is not unique")
source_text = source_text.replace(old_compile, patch_generated_gate, 1)

code = compile(source_text, str(Path(__file__)), "exec")
exec(code, {"__name__": "__main__", "__file__": str(Path(__file__))})

