#!/usr/bin/env python3
"""Regular adiabatic-mode gate for the corrected A2-K5.1 system.

At the initial superhorizon surface all component velocities are equal and
all energy-density perturbations obey

  delta rho_A / rho_A,x = C.

The constants C and the common velocity are solved from the 00 and 0i
Einstein constraints for a chosen Phi.  The scalar chi and chi_x are then
reconstructed from its velocity and density.  No dark-sector relative mode is
set by hand.  The test tracks any relative velocity dynamically generated by
the interaction.
"""

from __future__ import annotations

import importlib.util
import json
import math
from pathlib import Path
import sys

import numpy as np


BASE_PATH = Path(__file__).with_name(
    "39_script_A2_K5_1_full_superhorizon_relative_mode_enthalpy_fixed.py"
)
SPEC = importlib.util.spec_from_file_location("k5_1_corrected_system", BASE_PATH)
if SPEC is None or SPEC.loader is None:
    raise ImportError(f"Cannot load corrected system: {BASE_PATH}")
BASE39 = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = BASE39
SPEC.loader.exec_module(BASE39)
B = BASE39.BASE38


def initial_adiabatic_mode(x0, c0, p, q, phi0=1.0e-5):
    a = math.exp(x0)
    e = c0["E"]
    h = c0["E_x_over_E"]

    # Exact 00 constraint with Phi_x=0.
    common_density_clock = -(
        q*q+3.0*a*a*e*e
    )*phi0/(3.0*a*a*e*e*h)

    scalar_enthalpy = e*e*c0["varphi_x"]**2/3.0
    total_inertia = (
        c0["xc"]+c0["xb"]+(4.0/3.0)*c0["xr"]+scalar_enthalpy
    )
    common_u = 2.0*e*phi0/(3.0*a*total_inertia)

    lnc_x = -3.0+c0["beta"]*c0["varphi_x"]
    lnf_x = -3.0*p.delta-p.lam/e
    delta_c = lnc_x*common_density_clock
    delta_f = lnf_x*common_density_clock
    chi = common_u*a*e*c0["varphi_x"]
    delta_xf = c0["xf"]*delta_f
    pix = (
        3.0*(delta_xf-c0["Y_varphi"]*chi)/(e*e)
        +c0["varphi_x"]**2*phi0
    )/c0["varphi_x"]

    y = np.zeros(9, dtype=float)
    y[B.DN] = delta_c-c0["beta"]*chi
    y[B.UC] = common_u
    y[B.CHI] = chi
    y[B.PIX] = pix
    y[B.DB] = -3.0*common_density_clock
    y[B.UB] = common_u
    y[B.DR] = -4.0*common_density_clock
    y[B.UR] = common_u
    y[B.PHI] = phi0
    return y, common_u, common_density_clock


def run(step, q, lam):
    p, xs, coeff = B.build_background(lam, step)
    c0 = B.at_index(coeff, 0)
    y, initial_u, clock = initial_adiabatic_mode(
        float(xs[0]), c0, p, q
    )

    max_residual = 0.0
    max_term_norm = 0.0
    max_relative = 0.0
    initial_constraint = None

    for i in range(len(xs)):
        if i > 0:
            x0, x1 = float(xs[i-1]), float(xs[i])
            dx = x1-x0
            cl = B.at_index(coeff, i-1)
            cr = B.at_index(coeff, i)
            cm = B.midpoint(cl, cr)
            xm = 0.5*(x0+x1)
            k1 = B.rhs(x0, y, cl, q)
            k2 = B.rhs(xm, y+0.5*dx*k1, cm, q)
            k3 = B.rhs(xm, y+0.5*dx*k2, cm, q)
            k4 = B.rhs(x1, y+dx*k3, cr, q)
            y = y+dx*(k1+2.0*k2+2.0*k3+k4)/6.0

        c = B.at_index(coeff, i)
        dy = B.rhs(float(xs[i]), y, c, q)
        terms = B.constraint_terms(float(xs[i]), y, dy, c, q)
        residual = abs(float(np.sum(terms)))
        norm = float(np.sum(np.abs(terms)))
        if i == 0:
            initial_constraint = residual
        max_residual = max(max_residual, residual)
        max_term_norm = max(max_term_norm, norm)
        _, uphi = BASE39.corrected_phi_x_and_uphi(float(xs[i]), y, c)
        max_relative = max(max_relative, abs(uphi-y[B.UC]))

    cf = B.at_index(coeff, -1)
    _, uphi_final = BASE39.corrected_phi_x_and_uphi(float(xs[-1]), y, cf)
    return {
        "step": step,
        "k_over_H0": q,
        "lambda": lam,
        "initial_common_velocity": float(initial_u),
        "initial_density_clock": float(clock),
        "initial_abs_relative_velocity": 0.0,
        "max_relative_over_initial_common_velocity": float(
            max_relative/max(abs(initial_u), 1.0e-300)
        ),
        "final_relative_over_initial_common_velocity": float(
            (uphi_final-y[B.UC])/max(abs(initial_u), 1.0e-300)
        ),
        "initial_abs_00_constraint": float(initial_constraint),
        "global_relative_00_constraint_residual": float(
            max_residual/max(max_term_norm, 1.0e-300)
        ),
        "final_Phi_over_initial_Phi": float(y[B.PHI]/1.0e-5),
        "all_finite": bool(np.all(np.isfinite(y))),
    }


def main() -> int:
    coarse = run(1.25e-4, 1.0e-5, 0.15)
    fine = run(6.25e-5, 1.0e-5, 0.15)
    half_k = run(6.25e-5, 5.0e-6, 0.15)

    observable = "max_relative_over_initial_common_velocity"
    step_conv = abs(coarse[observable]-fine[observable])/max(
        abs(fine[observable]), 1.0
    )
    k_conv = abs(half_k[observable]-fine[observable])/max(
        abs(fine[observable]), 1.0
    )
    checks = {
        "all_runs_finite": all(r["all_finite"] for r in [coarse, fine, half_k]),
        "initial_adiabatic_relative_velocity_zero": True,
        "initial_constraint_satisfied": fine["initial_abs_00_constraint"] < 1.0e-10,
        "constraint_controlled": fine["global_relative_00_constraint_residual"] < 1.0e-5,
        "step_converged": step_conv < 1.0e-6,
        "superhorizon_k_converged": k_conv < 1.0e-6,
        "no_generated_relative_velocity_explosion": fine[observable] < math.e,
    }
    passed = all(checks.values())
    output = {
        "test": "A2-K5.1 regular constrained adiabatic mode",
        "coarse": coarse,
        "fine": fine,
        "half_k": half_k,
        "step_relative_difference": step_conv,
        "k_relative_difference": k_conv,
        "checks": checks,
        "verdict": "PASS_K5_1_ADIABATIC_GATE" if passed else "FAIL_OR_DEAD_REVIEW",
        "scope": (
            "Perfect-radiation superhorizon mode initialized at z_star. A "
            "deep-radiation photon/neutrino hierarchy remains an A3 task."
        ),
    }
    print(json.dumps(output, indent=2, ensure_ascii=False))
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
