#!/usr/bin/env python3
"""A2-K7.1a-K1: constant-width on-shell mediator cascade audit.

The K7.0 exact-background split assumes

    rho_M = epsilon rho_F,            0 < epsilon < delta,
    Q2 = Gamma rho_F,
    Q1 = [(1-epsilon) Gamma + 3 H epsilon (1-delta)] rho_F.

For the simplest local Markovian decay chain with constant proper-time
widths,

    Q2 = Gamma_chi rho_M,
    Q1 = Gamma_phi rho_phi,

the exact K7.0 background requires

    Gamma_chi/H0 = lambda/epsilon,
    Gamma_phi,required/H0
      = lambda + 3 E(a) epsilon (1-delta)/(1-epsilon).

The second expression cannot be a constant width in an evolving FRW
background for epsilon>0 and delta!=1.  This script quantifies the mismatch
on the already validated A1 background.  It kills only the fixed-width
subtrack K7.1a-K1, not every possible finite-enthalpy mediator mechanism.
"""

from __future__ import annotations

import importlib.util
import math
from pathlib import Path
import sys

import numpy as np


SOURCE = Path(__file__).with_name(
    "50_script_A2_K7_0_mediator_ledger_collision_gate.py"
)
SPEC = importlib.util.spec_from_file_location("k7_0_base", SOURCE)
if SPEC is None or SPEC.loader is None:
    raise ImportError(f"Cannot load {SOURCE}")
K70 = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = K70
SPEC.loader.exec_module(K70)


def audit_fraction(base: dict, fraction: float) -> dict:
    p = base["p"]
    e = base["e"]
    epsilon = fraction * p.delta

    gamma_chi_over_h0 = p.lam / epsilon
    gamma_phi_required = (
        p.lam
        + 3.0 * e * epsilon * (1.0 - p.delta) / (1.0 - epsilon)
    )
    upsilon_required = (
        (1.0 - epsilon) * p.lam
        + 3.0 * e * epsilon * (1.0 - p.delta)
    ) / (p.delta - epsilon)

    variation = float(np.max(gamma_phi_required) / np.min(gamma_phi_required))
    upsilon_variation = float(np.max(upsilon_required) / np.min(upsilon_required))
    gamma_chi_over_h = gamma_chi_over_h0 / e

    # A constant width can match all times only in one of the degenerate
    # cases epsilon=0, delta=1, or E(a)=constant.  None applies to K7.0.
    fixed_width_identity_possible = bool(
        epsilon == 0.0
        or p.delta == 1.0
        or np.allclose(e, e[0], rtol=0.0, atol=0.0)
    )

    return {
        "fraction": fraction,
        "epsilon": epsilon,
        "E_recombination": float(e[0]),
        "E_today": float(e[-1]),
        "Gamma_chi_over_H0": gamma_chi_over_h0,
        "Gamma_chi_over_H_recombination": float(gamma_chi_over_h[0]),
        "Gamma_chi_over_H_today": float(gamma_chi_over_h[-1]),
        "Gamma_phi_required_over_H0_recombination": float(
            gamma_phi_required[0]
        ),
        "Gamma_phi_required_over_H0_today": float(gamma_phi_required[-1]),
        "Gamma_phi_required_max_to_min": variation,
        "Upsilon_required_over_H0_recombination": float(upsilon_required[0]),
        "Upsilon_required_over_H0_today": float(upsilon_required[-1]),
        "Upsilon_required_max_to_min": upsilon_variation,
        "fixed_Gamma_chi_matches_Q2": True,
        "fixed_Gamma_phi_matches_Q1_at_all_times": fixed_width_identity_possible,
    }


def main() -> int:
    base = K70.background(2.5e-4)
    rows = [
        audit_fraction(base, fraction)
        for fraction in K70.EPSILON_OVER_DELTA_GRID
    ]

    print("# A2-K7.1a-K1 — constant-width cascade no-go")
    print()
    print("The exact K7.0 Q2 can be generated by a constant mediator width")
    print("`Gamma_chi/H0=lambda/epsilon`.  The required production width")
    print("contains an unavoidable term proportional to the evolving `E(a)`." )
    print()
    print(
        "| eps/delta | epsilon | E(rec) | Gamma_chi/H0 | "
        "Gamma_chi/H(rec) | Gamma_phi/H0 rec | Gamma_phi/H0 now | "
        "max/min Gamma_phi | fixed-width Q1 |"
    )
    print("|---:|---:|---:|---:|---:|---:|---:|---:|:---:|")
    for row in rows:
        print(
            f"| {row['fraction']:.2f} | {row['epsilon']:.8f} | "
            f"{row['E_recombination']:.6f} | "
            f"{row['Gamma_chi_over_H0']:.6f} | "
            f"{row['Gamma_chi_over_H_recombination']:.6e} | "
            f"{row['Gamma_phi_required_over_H0_recombination']:.6f} | "
            f"{row['Gamma_phi_required_over_H0_today']:.6f} | "
            f"{row['Gamma_phi_required_max_to_min']:.6f} | "
            f"{'PASS' if row['fixed_Gamma_phi_matches_Q1_at_all_times'] else 'FAIL'} |"
        )

    all_q2 = all(row["fixed_Gamma_chi_matches_Q2"] for row in rows)
    any_q1 = any(
        row["fixed_Gamma_phi_matches_Q1_at_all_times"] for row in rows
    )
    print()
    print("## Checks")
    print()
    print(f"- constant-width `chi -> c c` reproduces Q2: `{all_q2}`;")
    print(f"- constant-width `phi -> chi` reproduces Q1 for any grid point: `{any_q1}`;")
    print("- the failure is algebraic, not an integration-tolerance failure;")
    print("- a local time-dependent/open-system coefficient is a different subtrack.")
    print()
    print("## Verdict")
    print()
    print("`A2-K7.1a-K1 MŔTVA M-014a`: the fixed-width on-shell cascade cannot")
    print("reproduce the exact constant-epsilon K7.0 source Q1 over an evolving")
    print("background.  This does not kill K7.1a-K2/K3 alternatives.")
    return 1 if not any_q1 else 0


if __name__ == "__main__":
    raise SystemExit(main())
