#!/usr/bin/env python
"""Emit the A2-K4.3b-RG 77--86 SHA-256 manifest with a hard deadline."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import time


ROOT = Path(__file__).resolve().parents[1]
FILES = (
    "scripts/77_script_A2_K4_3b_RG_collective_CAMB_regular_seed_audit.py",
    "scripts/78_script_A2_K4_3b_RG_collective_CAMB_regular_seed_active_start_fixed.py",
    "scripts/79_script_A2_K4_3b_RG_collective_CAMB_regular_seed_precompiled_only.py",
    "scripts/80_script_A2_K4_3b_RG_internal_nu_steam_exact_regular_series.py",
    "scripts/81_script_A2_K4_3b_RG_CAMB_Newtonian_metric_reconstruction_audit.py",
    "scripts/82_script_A2_K4_3b_RG_CAMB_Newtonian_metric_reconstruction_fine_grid.py",
    "scripts/83_script_A2_K4_3b_RG_exact_background_fractional_power_audit.py",
    "scripts/84_script_A2_K4_3b_RG_CLASS_analytic_collective_seed_CAMB_crosscheck.py",
    "scripts/85_script_A2_K4_3b_RG_collective_K4_test_field_Puiseux_response.py",
    "scripts/86_script_A2_K4_3b_RG_general_synchronous_K4_test_field_response.py",
    "scripts/ERRATUM_77_A2_K4_3b_CAMB_ZERO_PLACEHOLDER_START.md",
    "scripts/ERRATUM_78_A2_K4_3b_SYMBOLIC_COMPILER_UNAVAILABLE.md",
    "scripts/ERRATUM_81_A2_K4_3b_SPARSE_DERIVATIVE_GRID.md",
    "scripts/ERRATUM_85_A2_K4_3b_TRUNCATED_NEWTONIAN_GAUGE_MAP.md",
    "scripts/OUTPUT_A2_K4_3B_RG_77_86.md",
    "Audit/A2_K4_3B_RG_REGULAR_SEEDS_PUISEUX_AND_SYNCHRONOUS_TEST_FIELD_AUDIT.md",
    "Questions/00_READ_FIRST_A2_Q20_AFTER_K4_3B_RG_86.md",
    "Questions/A2_K4_3B_RG_STAV_A_DALSI_KROK_PO_86.md",
    "Questions/00_AKCNY_PLAN_v3.18_ADDENDUM_K4_3B_RG_86.md",
    "theory/SK/05zzzzzz_Methodology_Rules_and_Question_Register_A2_K4_3b_RG_SK.md",
    "theory/EN/05zzzzzz_Methodology_Rules_and_Question_Register_A2_K4_3b_RG_EN.md",
)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-runtime-seconds", type=float, default=15.0)
    args = parser.parse_args()
    if not (0.0 < args.max_runtime_seconds <= 20.0):
        parser.error("--max-runtime-seconds must be in (0,20]")
    started = time.monotonic()
    rows: list[tuple[str, str]] = []
    for relative in FILES:
        if time.monotonic() - started > args.max_runtime_seconds:
            raise TimeoutError("manifest hashing deadline exceeded")
        path = ROOT / relative
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        rows.append((digest, relative))
    print("# A2-K4.3b-RG 77--86 manifest SHA-256")
    print()
    print("Generated by `87_script_A2_K4_3b_RG_manifest_sha256.py`.")
    print()
    print("```text")
    for digest, relative in rows:
        print(f"{digest}  {relative}")
    print("```")
    print()
    print(f"Runtime: `{time.monotonic() - started:.6f} s`; internal limit: `{args.max_runtime_seconds} s`.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except TimeoutError as exc:
        print(f"TIMEOUT_UNCLOSED: {exc}")
        raise SystemExit(124)
