#!/usr/bin/env python
"""Emit the K4.3b-RG-BR 88--95 package SHA-256 manifest."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import time

ROOT=Path(__file__).resolve().parents[1]
FILES=(
 "scripts/88_script_A2_K4_3b_RG_BR1_synchronous_Einstein_and_transfer_ledger.py",
 "scripts/89_script_A2_K4_3b_RG_BR2_backreacted_superhorizon_evolution.py",
 "scripts/90_script_A2_K4_3b_RG_BR2_conditioned_DAE_constraint_audit.py",
 "scripts/91_script_A2_K4_3b_RG_BR2_Omega_conditioned_DAE.py",
 "scripts/91_script_A2_K4_3b_RG_BR2_Omega_conditioned_DAE_ERRATUM.md",
 "scripts/92_script_A2_K4_3b_RG_BR2_Omega_conditioned_DAE_json_fixed_alias.py",
 "scripts/93_script_A2_K4_3b_RG_BR2_velocity_roundoff_condition_gate.py",
 "scripts/93_script_A2_K4_3b_RG_BR2_velocity_roundoff_condition_gate_ERRATUM.md",
 "scripts/94_script_A2_K4_3b_RG_BR2_velocity_roundoff_condition_gate_json_alias.py",
 "scripts/95_script_A2_K4_3b_RG_BR3A_mode_resolved_Puiseux_sources.py",
 "scripts/OUTPUT_A2_K4_3B_RG_BR_88_95.md",
 "Audit/A2_K4_3B_RG_BR1_BR2_BR3A_AUDIT.md",
 "Questions/00_READ_FIRST_A2_Q20_AFTER_K4_3B_RG_BR3A_95.md",
 "Questions/A2_K4_3B_RG_BR_STAV_A_DALSI_KROK_PO_95.md",
 "Questions/00_AKCNY_PLAN_v3.18_ADDENDUM_K4_3B_RG_BR3A_95.md",
 "theory/SK/05zzzzzzz_Methodology_Rules_and_Question_Register_A2_K4_3b_BR_SK.md",
 "theory/EN/05zzzzzzz_Methodology_Rules_and_Question_Register_A2_K4_3b_BR_EN.md",
)


def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--max-runtime-seconds",type=float,default=10.)
    a=ap.parse_args()
    if not (0<a.max_runtime_seconds<=15): ap.error("runtime must be in (0,15]")
    t=time.monotonic(); rows=[]
    for rel in FILES:
        if time.monotonic()-t>a.max_runtime_seconds: raise TimeoutError("manifest deadline exceeded")
        rows.append((hashlib.sha256((ROOT/rel).read_bytes()).hexdigest(),rel))
    print("# A2-K4.3b-RG-BR 88--95 manifest SHA-256\n")
    print("Generated by `96_script_A2_K4_3b_RG_BR_88_95_manifest_sha256.py`.\n")
    print("```text")
    for digest,rel in rows: print(f"{digest}  {rel}")
    print("```\n")
    print(f"Runtime: `{time.monotonic()-t:.6f} s`; internal limit: `{a.max_runtime_seconds} s`.")
    return 0


if __name__=="__main__":
    try: raise SystemExit(main())
    except TimeoutError as exc:
        print(f"TIMEOUT_UNCLOSED: {exc}"); raise SystemExit(124)
